#!/usr/bin/env python3
"""
Quality gate for Academic Author DNA skills generated by Distiller-DNA-by-Sora.
Checks Hybrid / DNA Kernel / Open Framework readiness.

Usage:
    python3 quality_check.py <SKILL.md>
"""
import re
import sys
from pathlib import Path


def section(content: str, title_regex: str) -> str:
    m = re.search(rf"^##\s+.*(?:{title_regex}).*$(.*?)(?=^##\s+|\Z)", content, re.I | re.M | re.S)
    return m.group(1) if m else ""


def count_items(text: str) -> int:
    return len(re.findall(r"^\s*[-*]\s+", text, re.M))


def check_mode_profile(content: str):
    has = bool(re.search(r"Mode Profile|Distillation mode|Hybrid|DNA Kernel|Open Framework", content, re.I))
    return has, "mode profile / mode markers present" if has else "missing mode profile or mode markers"


def check_dna_kernel(content: str):
    kernel = section(content, r"DNA Kernel|Research DNA|Research Lenses|Research Primitives")
    primitive_count = len(re.findall(r"^###\s+(?:Primitive|Lens|Research).*", kernel or content, re.I | re.M))
    has_failure = bool(re.search(r"Failure mode|失效|局限|边界|failure", kernel or content, re.I))
    has_distinct = bool(re.search(r"Distinctiveness|独特|排他|不是.*通用", kernel or content, re.I))
    passed = primitive_count >= 3 and has_failure and has_distinct
    return passed, f"primitives/lenses={primitive_count}, failure={has_failure}, distinctiveness={has_distinct}"


def check_method_dna(content: str):
    text = section(content, r"Method DNA|方法DNA")
    count = count_items(text)
    passed = count >= 5 or bool(re.search(r"Evidence Standard|证据标准", content, re.I))
    return passed, f"method rules={count} (expected >=5, or evidence-standard section present)"


def check_writing_dna(content: str):
    text = section(content, r"Writing DNA|Paper Writing DNA|写作DNA")
    required = ["Abstract", "Introduction", "Method", "Results", "Limitations"]
    hits = sum(1 for r in required if re.search(r, text, re.I))
    # Chinese fallback
    if hits < 3:
        zh = ["摘要", "引言", "方法", "结果", "限制"]
        hits = max(hits, sum(1 for r in zh if r in text))
    passed = hits >= 4
    return passed, f"writing coverage hits={hits}/5"


def check_open_framework(content: str):
    has_field = bool(re.search(r"Research Field Map|Field Map|问题域|研究场", content, re.I))
    has_evolution = bool(re.search(r"Evolution Timeline|思想演化|演化|timeline", content, re.I))
    has_tension = bool(re.search(r"Tension Ledger|Academic Tensions|张力|矛盾", content, re.I))
    has_open = bool(re.search(r"Open Problems|未完成问题|开放问题", content, re.I))
    passed = sum([has_field, has_evolution, has_tension, has_open]) >= 3
    return passed, f"field={has_field}, evolution={has_evolution}, tension={has_tension}, open_problems={has_open}"


def check_review_dna(content: str):
    text = section(content, r"Review DNA|Critique DNA|审稿|评审")
    count = count_items(text)
    has_review = bool(text.strip()) or bool(re.search(r"novelty|soundness|significance|reproducibility|rebuttal|审稿|复现", content, re.I))
    passed = has_review and (count >= 3 or bool(re.search(r"check", text, re.I)))
    return passed, f"review section={has_review}, items={count}"


def check_boundaries(content: str):
    text = section(content, r"Honest Boundaries|Safe Identity|安全|边界|诚信")
    markers = ["impersonat", "fabricat", "citation", "plagiarism", "endorse", "private", "伪造", "引用", "背书", "剽窃", "作者本人"]
    hits = sum(1 for m in markers if re.search(m, text or content, re.I))
    passed = hits >= 4
    return passed, f"safety/boundary markers={hits}"


def check_source_ledger(content: str):
    has = bool(re.search(r"Source Ledger|来源|primary|secondary|inferred|DOI|arXiv", content, re.I))
    return has, "source ledger/evidence markers present" if has else "missing source ledger/evidence markers"


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 quality_check.py <SKILL.md>")
        sys.exit(1)
    path = Path(sys.argv[1])
    if not path.exists():
        print(f"❌ file not found: {path}")
        sys.exit(1)
    content = path.read_text(encoding="utf-8")

    checks = [
        ("Mode profile", check_mode_profile),
        ("DNA Kernel", check_dna_kernel),
        ("Method DNA", check_method_dna),
        ("Writing DNA", check_writing_dna),
        ("Open Framework", check_open_framework),
        ("Review DNA", check_review_dna),
        ("Honest boundaries", check_boundaries),
        ("Source ledger", check_source_ledger),
    ]

    passed = 0
    print(f"Quality check: {path}")
    print("=" * 60)
    for name, fn in checks:
        ok, msg = fn(content)
        print(f"{name:<18} {'✅ PASS' if ok else '❌ FAIL'}  {msg}")
        passed += int(ok)
    print("=" * 60)
    print(f"Result: {passed}/{len(checks)} passed")
    if passed == len(checks):
        print("🎉 Ready to ship")
    elif passed >= len(checks) - 2:
        print("⚠️ Usable, but fix weak gates before high-stakes use")
    else:
        print("❌ Not ready; revise extraction or boundaries")
        sys.exit(2)


if __name__ == '__main__':
    main()
